#include "stdafx.h"
#include "sdl.h"
#include "sdl_event_generator.h"

static vector<SDL::SDL_Keycode> syms {
  SDLK_UNKNOWN,
  SDLK_RETURN,
  SDLK_ESCAPE,
  SDLK_BACKSPACE,
  SDLK_TAB,
  SDLK_SPACE,
  SDLK_EXCLAIM,
  SDLK_DBLAPOSTROPHE,
  SDLK_HASH,
  SDLK_PERCENT,
  SDLK_DOLLAR,
  SDLK_AMPERSAND,
  SDLK_APOSTROPHE,
  SDLK_LEFTPAREN,
  SDLK_RIGHTPAREN,
  SDLK_ASTERISK,
  SDLK_PLUS,
  SDLK_COMMA,
  SDLK_MINUS,
  SDLK_PERIOD,
  SDLK_SLASH,
  SDLK_0,
  SDLK_1,
  SDLK_2,
  SDLK_3,
  SDLK_4,
  SDLK_5,
  SDLK_6,
  SDLK_7,
  SDLK_8,
  SDLK_9,
  SDLK_COLON,
  SDLK_SEMICOLON,
  SDLK_LESS,
  SDLK_EQUALS,
  SDLK_GREATER,
  SDLK_QUESTION,
  SDLK_AT,
  SDLK_LEFTBRACKET,
  SDLK_BACKSLASH,
  SDLK_RIGHTBRACKET,
  SDLK_CARET,
  SDLK_UNDERSCORE,
  SDLK_GRAVE,
  SDLK_A,
  SDLK_B,
  SDLK_C,
  SDLK_D,
  SDLK_E,
  SDLK_F,
  SDLK_G,
  SDLK_H,
  SDLK_I,
  SDLK_J,
  SDLK_K,
  SDLK_L,
  SDLK_M,
  SDLK_N,
  SDLK_O,
  SDLK_P,
  SDLK_Q,
  SDLK_R,
  SDLK_S,
  SDLK_T,
  SDLK_U,
  SDLK_V,
  SDLK_W,
  SDLK_X,
  SDLK_Y,
  SDLK_Z,
  SDLK_CAPSLOCK,
  SDLK_F1,
  SDLK_F2,
  SDLK_F3,
  SDLK_F4,
  SDLK_F5,
  SDLK_F6,
  SDLK_F7,
  SDLK_F8,
  SDLK_F9,
  SDLK_F10,
  SDLK_F11,
  SDLK_F12,
  SDLK_PRINTSCREEN,
  SDLK_SCROLLLOCK,
  SDLK_PAUSE,
  SDLK_INSERT,
  SDLK_HOME,
  SDLK_PAGEUP,
  SDLK_DELETE,
  SDLK_END,
  SDLK_PAGEDOWN,
  SDLK_RIGHT,
  SDLK_LEFT,
  SDLK_DOWN,
  SDLK_UP,
  SDLK_NUMLOCKCLEAR,
  SDLK_KP_DIVIDE,
  SDLK_KP_MULTIPLY,
  SDLK_KP_MINUS,
  SDLK_KP_PLUS,
  SDLK_KP_ENTER,
  SDLK_KP_1,
  SDLK_KP_2,
  SDLK_KP_3,
  SDLK_KP_4,
  SDLK_KP_5,
  SDLK_KP_6,
  SDLK_KP_7,
  SDLK_KP_8,
  SDLK_KP_9,
  SDLK_KP_0,
  SDLK_KP_PERIOD,
  SDLK_APPLICATION,
  SDLK_POWER,
  SDLK_KP_EQUALS,
  SDLK_F13,
  SDLK_F14,
  SDLK_F15,
  SDLK_F16,
  SDLK_F17,
  SDLK_F18,
  SDLK_F19,
  SDLK_F20,
  SDLK_F21,
  SDLK_F22,
  SDLK_F23,
  SDLK_F24,
  SDLK_EXECUTE,
  SDLK_HELP,
  SDLK_MENU,
  SDLK_SELECT,
  SDLK_STOP,
  SDLK_AGAIN,
  SDLK_UNDO,
  SDLK_CUT,
  SDLK_COPY,
  SDLK_PASTE,
  SDLK_FIND,
  SDLK_MUTE,
  SDLK_VOLUMEUP,
  SDLK_VOLUMEDOWN,
  SDLK_KP_COMMA,
  SDLK_KP_EQUALSAS400,
  SDLK_ALTERASE,
  SDLK_SYSREQ,
  SDLK_CANCEL,
  SDLK_CLEAR,
  SDLK_PRIOR,
  SDLK_RETURN2,
  SDLK_SEPARATOR,
  SDLK_OUT,
  SDLK_OPER,
  SDLK_CLEARAGAIN,
  SDLK_CRSEL,
  SDLK_EXSEL,
  SDLK_KP_00,
  SDLK_KP_000,
  SDLK_THOUSANDSSEPARATOR,
  SDLK_DECIMALSEPARATOR,
  SDLK_CURRENCYUNIT,
  SDLK_CURRENCYSUBUNIT,
  SDLK_KP_LEFTPAREN,
  SDLK_KP_RIGHTPAREN,
  SDLK_KP_LEFTBRACE,
  SDLK_KP_RIGHTBRACE,
  SDLK_KP_TAB,
  SDLK_KP_BACKSPACE,
  SDLK_KP_A,
  SDLK_KP_B,
  SDLK_KP_C,
  SDLK_KP_D,
  SDLK_KP_E,
  SDLK_KP_F,
  SDLK_KP_XOR,
  SDLK_KP_POWER,
  SDLK_KP_PERCENT,
  SDLK_KP_LESS,
  SDLK_KP_GREATER,
  SDLK_KP_AMPERSAND,
  SDLK_KP_DBLAMPERSAND,
  SDLK_KP_VERTICALBAR,
  SDLK_KP_DBLVERTICALBAR,
  SDLK_KP_COLON,
  SDLK_KP_HASH,
  SDLK_KP_SPACE,
  SDLK_KP_AT,
  SDLK_KP_EXCLAM,
  SDLK_KP_MEMSTORE,
  SDLK_KP_MEMRECALL,
  SDLK_KP_MEMCLEAR,
  SDLK_KP_MEMADD,
  SDLK_KP_MEMSUBTRACT,
  SDLK_KP_MEMMULTIPLY,
  SDLK_KP_MEMDIVIDE,
  SDLK_KP_PLUSMINUS,
  SDLK_KP_CLEAR,
  SDLK_KP_CLEARENTRY,
  SDLK_KP_BINARY,
  SDLK_KP_OCTAL,
  SDLK_KP_DECIMAL,
  SDLK_KP_HEXADECIMAL,
  SDLK_LCTRL,
  SDLK_LSHIFT,
  SDLK_LALT,
  SDLK_LGUI,
  SDLK_RCTRL,
  SDLK_RSHIFT,
  SDLK_RALT,
  SDLK_RGUI,
  SDLK_MODE,
  SDLK_MEDIA_NEXT_TRACK,
  SDLK_MEDIA_PREVIOUS_TRACK,
  SDLK_MEDIA_STOP,
  SDLK_MEDIA_PLAY,
  SDLK_MUTE,
  SDLK_MEDIA_SELECT,
  SDLK_AC_SEARCH,
  SDLK_AC_HOME,
  SDLK_AC_BACK,
  SDLK_AC_FORWARD,
  SDLK_AC_STOP,
  SDLK_AC_REFRESH,
  SDLK_AC_BOOKMARKS,
  SDLK_SLEEP
};

SDL::SDL_Event SdlEventGenerator::getRandom(RandomGen& random, Vec2 screenSize) {
  SDL::SDL_Event ret;
  memset(&ret, 0, sizeof(ret));
  ret.type = random.choose(
      SDL::SDL_EVENT_KEY_DOWN,
      SDL::SDL_EVENT_MOUSE_BUTTON_DOWN,
      SDL::SDL_EVENT_MOUSE_BUTTON_UP,
      SDL::SDL_EVENT_MOUSE_WHEEL,
      SDL::SDL_EVENT_MOUSE_MOTION
  );
  int modProb = 5;
  switch (ret.type) {
    case SDL::SDL_EVENT_KEY_DOWN:
      ret.key.type = (SDL::SDL_EventType) ret.type;
      ret.key.down = true;
      ret.key.repeat = random.roll(modProb);
      ret.key.scancode = (SDL::SDL_Scancode) random.get(SDL::SDL_SCANCODE_COUNT);
      ret.key.key = random.choose(syms);
      ret.key.mod = (SDL::SDL_Keymod) (int) random.choose(SDL_KMOD_LSHIFT, SDL_KMOD_RSHIFT,
          SDL_KMOD_LCTRL, SDL_KMOD_RCTRL, SDL_KMOD_LALT, SDL_KMOD_RALT);
      break;
    case SDL::SDL_EVENT_MOUSE_BUTTON_DOWN:
      ret.button.type = (SDL::SDL_EventType) ret.type;
      ret.button.button = (SDL::Uint8) random.choose(SDL_BUTTON_RIGHT, SDL_BUTTON_LEFT, SDL_BUTTON_MIDDLE);
      ret.button.down = true;
      ret.button.clicks = 1;
      ret.button.x = (float) random.get(screenSize.x);
      ret.button.y = (float) random.get(screenSize.y);
      break;
    case SDL::SDL_EVENT_MOUSE_BUTTON_UP:
      ret.button.type = (SDL::SDL_EventType) ret.type;
      ret.button.button = (SDL::Uint8) random.choose(SDL_BUTTON_RIGHT, SDL_BUTTON_LEFT, SDL_BUTTON_MIDDLE);
      ret.button.down = false;
      ret.button.clicks = 1;
      ret.button.x = (float) random.get(screenSize.x);
      ret.button.y = (float) random.get(screenSize.y);
      break;
    case SDL::SDL_EVENT_MOUSE_MOTION:
      ret.motion.type = (SDL::SDL_EventType) ret.type;
      ret.motion.x = (float) random.get(screenSize.x);
      ret.motion.y = (float) random.get(screenSize.y);
      break;
    case SDL::SDL_EVENT_MOUSE_WHEEL:
      ret.wheel.type = (SDL::SDL_EventType) ret.type;
      ret.wheel.y = (float) random.choose(-1, 1);
      ret.wheel.direction = SDL::SDL_MOUSEWHEEL_NORMAL;
      break;
  }
  return ret;
}
